// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include "UI.h"

void GUI::cb_Load_i(Fl_Button*, void*) {
  Fl_File_Chooser chooser("C:/code/printed-parts", "*.stl", Fl_File_Chooser::SINGLE, "Choose GCode");
chooser.show();
while (chooser.shown())
	Fl::wait();
if(chooser.value() == 0)
	return;
std::string dir(chooser.value());


if(dir.length())
{
MVC->ReadStl(dir);
MVC->redraw();
};
}
void GUI::cb_Load(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_Load_i(o,v);
}

void GUI::cb_FixSTLerrorsButton_i(Fl_Light_Button*, void*) {
  MVC->redraw();
}
void GUI::cb_FixSTLerrorsButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_FixSTLerrorsButton_i(o,v);
}

void GUI::cb_Save_i(Fl_Button*, void*) {
  Fl_File_Chooser chooser("C:/code/printed-parts", "*.stl", Fl_File_Chooser::SINGLE, "Choose GCode");
chooser.show();
while (chooser.shown())
	Fl::wait();
if(chooser.value() == 0)
	return;
std::string dir(chooser.value());


if(dir.length())
{
MVC->ReadStl(dir);
MVC->redraw();
};
}
void GUI::cb_Save(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_Save_i(o,v);
}

void GUI::cb_Scale_i(Fl_Button*, void*) {
  Fl_File_Chooser chooser("C:/code/printed-parts", "*.stl", Fl_File_Chooser::SINGLE, "Choose GCode");
chooser.show();
while (chooser.shown())
	Fl::wait();
if(chooser.value() == 0)
	return;
std::string dir(chooser.value());


if(dir.length())
{
MVC->ReadStl(dir);
MVC->redraw();
};
}
void GUI::cb_Scale(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_Scale_i(o,v);
}

void GUI::cb_AutoRotateButton_i(Fl_Button*, void*) {
  MVC->OptimizeRotation();
MVC->CalcBoundingBoxAndZoom();
MVC->redraw();
}
void GUI::cb_AutoRotateButton(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_AutoRotateButton_i(o,v);
}

void GUI::cb_RotateXButton_i(Fl_Button*, void*) {
  MVC->RotateObject(1,0,0, M_PI/4);
MVC->CalcBoundingBoxAndZoom();
MVC->redraw();
}
void GUI::cb_RotateXButton(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RotateXButton_i(o,v);
}

void GUI::cb_RotateYButton_i(Fl_Button*, void*) {
  MVC->RotateObject(0,1,0, M_PI/4);
MVC->CalcBoundingBoxAndZoom();
MVC->redraw();
}
void GUI::cb_RotateYButton(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RotateYButton_i(o,v);
}

void GUI::cb_RotateZButton_i(Fl_Button*, void*) {
  MVC->RotateObject(0,0,1, M_PI/4);
MVC->CalcBoundingBoxAndZoom();
MVC->redraw();
}
void GUI::cb_RotateZButton(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RotateZButton_i(o,v);
}

void GUI::cb_accelerationStepsSlider_i(Fl_Value_Slider* o, void*) {
  MVC->NumAccelerationSteps(o->value());
}
void GUI::cb_accelerationStepsSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_accelerationStepsSlider_i(o,v);
}

void GUI::cb_distanceBetweenSpeedStepsSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetDistancePrAccelerationStep(o->value());
}
void GUI::cb_distanceBetweenSpeedStepsSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_distanceBetweenSpeedStepsSlider_i(o,v);
}

void GUI::cb_EnableAccelerationButton_i(Fl_Light_Button* o, void*) {
  MVC->SetEnableAcceleration(o->value());
if(o->value())
{
accelerationStepsSlider->activate();
distanceBetweenSpeedStepsSlider->activate();
UseFirmwareAccelerationButton->activate();
}
else
{
accelerationStepsSlider->deactivate();
distanceBetweenSpeedStepsSlider->deactivate();
UseFirmwareAccelerationButton->deactivate();
};
}
void GUI::cb_EnableAccelerationButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_EnableAccelerationButton_i(o,v);
}

void GUI::cb_UseFirmwareAccelerationButton_i(Fl_Light_Button* o, void*) {
  MVC->SetUseFirmwareAcceleration(o->value());

if(o->value())
{
accelerationStepsSlider->deactivate();
distanceBetweenSpeedStepsSlider->label("Distance used to read full speed(mm)");;
}
else
{
accelerationStepsSlider->activate();
distanceBetweenSpeedStepsSlider->label("Distance Pr Acceleration Step (mm)");;
}
accelerationStepsSlider->redraw();
distanceBetweenSpeedStepsSlider->redraw();
}
void GUI::cb_UseFirmwareAccelerationButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_UseFirmwareAccelerationButton_i(o,v);
}

void GUI::cb_MaxPrintSpeedXYSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetMaxPrintSpeedXY(o->value());
}
void GUI::cb_MaxPrintSpeedXYSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_MaxPrintSpeedXYSlider_i(o,v);
}

void GUI::cb_MinPrintSpeedZSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetMinPrintSpeedZ(o->value());
}
void GUI::cb_MinPrintSpeedZSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_MinPrintSpeedZSlider_i(o,v);
}

void GUI::cb_MinPrintSpeedXYSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetMinPrintSpeedXY(o->value());
}
void GUI::cb_MinPrintSpeedXYSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_MinPrintSpeedXYSlider_i(o,v);
}

void GUI::cb_MaxPrintSpeedZSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetMaxPrintSpeedZ(o->value());
}
void GUI::cb_MaxPrintSpeedZSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_MaxPrintSpeedZSlider_i(o,v);
}

void GUI::cb_ExtrudedMaterialWidthSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetExtrudedMaterialWidth(o->value());
}
void GUI::cb_ExtrudedMaterialWidthSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_ExtrudedMaterialWidthSlider_i(o,v);
}

void GUI::cb_extrusionFactorSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetExtrusionFactor(o->value());
}
void GUI::cb_extrusionFactorSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_extrusionFactorSlider_i(o,v);
}

void GUI::cb_UseIncrementalEcodeButton_i(Fl_Light_Button* o, void*) {
  MVC->SetUseIncrementalEcode(o->value());
}
void GUI::cb_UseIncrementalEcodeButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_UseIncrementalEcodeButton_i(o,v);
}

void GUI::cb_InfillRotationSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetInfillRotation(o->value());
}
void GUI::cb_InfillRotationSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_InfillRotationSlider_i(o,v);
}

void GUI::cb_InfillRotationPrLayerSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetInfillRotationPrLayer(o->value());
}
void GUI::cb_InfillRotationPrLayerSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_InfillRotationPrLayerSlider_i(o,v);
}

void GUI::cb_InfillDistanceSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetInfillDistance(o->value());
}
void GUI::cb_InfillDistanceSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_InfillDistanceSlider_i(o,v);
}

void GUI::cb_LayerThicknessSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetLayerThickness(o->value());
}
void GUI::cb_LayerThicknessSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_LayerThicknessSlider_i(o,v);
}

void GUI::cb_OptimizationSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetOptimization(o->value());
}
void GUI::cb_OptimizationSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_OptimizationSlider_i(o,v);
}

void GUI::cb_ShellOnlyButton_i(Fl_Light_Button* o, void*) {
  MVC->SetShellOnly(o->value());
}
void GUI::cb_ShellOnlyButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_ShellOnlyButton_i(o,v);
}

void GUI::cb_ShellCountSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetShellCount(o->value());
}
void GUI::cb_ShellCountSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_ShellCountSlider_i(o,v);
}

void GUI::cb_ApronSizeSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetApronSize(o->value());
}
void GUI::cb_ApronSizeSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_ApronSizeSlider_i(o,v);
}

void GUI::cb_ApronCoverageXSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetApronCoverageX(o->value());
}
void GUI::cb_ApronCoverageXSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_ApronCoverageXSlider_i(o,v);
}

void GUI::cb_ApronHeightSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetApronHeight(o->value());
}
void GUI::cb_ApronHeightSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_ApronHeightSlider_i(o,v);
}

void GUI::cb_ApronCoverageYSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetApronCoverageY(o->value());
}
void GUI::cb_ApronCoverageYSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_ApronCoverageYSlider_i(o,v);
}

void GUI::cb_ApronEnableButton_i(Fl_Light_Button* o, void*) {
  MVC->SetApronEnable(o->value());
}
void GUI::cb_ApronEnableButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_ApronEnableButton_i(o,v);
}

void GUI::cb_ApronDistanceToObjectSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetApronDistanceToObject(o->value());
}
void GUI::cb_ApronDistanceToObjectSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_ApronDistanceToObjectSlider_i(o,v);
}

void GUI::cb_ApronInfillDistanceSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetApronInfillDistance(o->value());
}
void GUI::cb_ApronInfillDistanceSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_ApronInfillDistanceSlider_i(o,v);
}

void GUI::cb_ApronPreviewButton_i(Fl_Light_Button* o, void*) {
  MVC->SetApronPreview(o->value());
}
void GUI::cb_ApronPreviewButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_ApronPreviewButton_i(o,v);
}

void GUI::cb_RaftMaterialPrDistanceRatioSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetRaftMaterialPrDistanceRatio(o->value());
}
void GUI::cb_RaftMaterialPrDistanceRatioSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RaftMaterialPrDistanceRatioSlider_i(o,v);
}

void GUI::cb_RaftRotationSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetRaftRotation(o->value());
}
void GUI::cb_RaftRotationSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RaftRotationSlider_i(o,v);
}

void GUI::cb_RaftBaseDistanceSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetRaftBaseDistance(o->value());
}
void GUI::cb_RaftBaseDistanceSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RaftBaseDistanceSlider_i(o,v);
}

void GUI::cb_RaftBaseThicknessSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetRaftBaseThickness(o->value());
}
void GUI::cb_RaftBaseThicknessSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RaftBaseThicknessSlider_i(o,v);
}

void GUI::cb_RaftBaseLayerCountSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetRaftBaseLayerCount(o->value());
}
void GUI::cb_RaftBaseLayerCountSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RaftBaseLayerCountSlider_i(o,v);
}

void GUI::cb_RaftBaseTemperatureSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetRaftBaseTemperature(o->value());
}
void GUI::cb_RaftBaseTemperatureSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RaftBaseTemperatureSlider_i(o,v);
}

void GUI::cb_RaftSizeSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetRaftSize(o->value());
}
void GUI::cb_RaftSizeSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RaftSizeSlider_i(o,v);
}

void GUI::cb_RaftInterfaceMaterialPrDistanceRatioSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetRaftInterfaceMaterialPrDistanceRatio(o->value());
}
void GUI::cb_RaftInterfaceMaterialPrDistanceRatioSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RaftInterfaceMaterialPrDistanceRatioSlider_i(o,v);
}

void GUI::cb_RaftRotationPrLayerSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetRaftRotationPrLayer(o->value());
}
void GUI::cb_RaftRotationPrLayerSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RaftRotationPrLayerSlider_i(o,v);
}

void GUI::cb_RaftInterfaceDistanceSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetRaftInterfaceDistance(o->value());
}
void GUI::cb_RaftInterfaceDistanceSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RaftInterfaceDistanceSlider_i(o,v);
}

void GUI::cb_RaftInterfaceThicknessSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetRaftBaseThickness(o->value());
}
void GUI::cb_RaftInterfaceThicknessSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RaftInterfaceThicknessSlider_i(o,v);
}

void GUI::cb_RaftInterfaceLayerCountSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SeRaftInterfaceLayerCount(o->value());
}
void GUI::cb_RaftInterfaceLayerCountSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RaftInterfaceLayerCountSlider_i(o,v);
}

void GUI::cb_RaftInterfaceTemperatureSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetRaftInterfaceTemperature(o->value());
}
void GUI::cb_RaftInterfaceTemperatureSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RaftInterfaceTemperatureSlider_i(o,v);
}

void GUI::cb_RaftEnableButton_i(Fl_Light_Button* o, void*) {
  MVC->SetRaftEnable(o->value());
}
void GUI::cb_RaftEnableButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_RaftEnableButton_i(o,v);
}

void GUI::cb_Preview_i(Fl_Light_Button* o, void*) {
  MVC->SetApronPreview(o->value());
}
void GUI::cb_Preview(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_Preview_i(o,v);
}

void GUI::cb_Load1_i(Fl_Button*, void*) {
  Fl_File_Chooser chooser("\\", "*.gcode", Fl_File_Chooser::SINGLE, "Choose GCode");
chooser.show();
while (chooser.shown())
	Fl::wait();
if(chooser.value() == 0)
	return;
std::string dir(chooser.value());


if(dir.length())
{
MVC->ReadGCode(dir);
MVC->redraw();
};
}
void GUI::cb_Load1(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_Load1_i(o,v);
}

void GUI::cb_Convert_i(Fl_Button*, void*) {
  MVC->ConvertToGCode();
}
void GUI::cb_Convert(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_Convert_i(o,v);
}

void GUI::cb_Save1_i(Fl_Button*, void*) {
  Fl_File_Chooser chooser("\\", "*.gcode", Fl_File_Chooser::CREATE, "Choose filename");
chooser.show();
while (chooser.shown())
	Fl::wait();
if(chooser.value() == 0)
	return;
std::string dir(chooser.value());


if(dir.length())
{
Fl_Text_Buffer *buffer = GCodeResult->buffer();

int result = buffer->savefile(chooser.value());

switch(result)
{
case 0:	// Succes
break;
case 1:	//Open for write failed
fl_alert("Error saving GCode file, error creating file.", "OK");
break;
case 2: // Partially saved file
fl_alert("Error saving GCode file, while writing file, is the disk full?.", "OK");
break;
}

MVC->redraw();
};
}
void GUI::cb_Save1(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_Save1_i(o,v);
}

void GUI::cb_DisplayPolygonsButton_i(Fl_Light_Button* o, void*) {
  MVC->SetDisplayPolygons(o->value());
}
void GUI::cb_DisplayPolygonsButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_DisplayPolygonsButton_i(o,v);
}

void GUI::cb_DisplayWireframeButton_i(Fl_Light_Button* o, void*) {
  MVC->SetDisplayWireframe(o->value());
}
void GUI::cb_DisplayWireframeButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_DisplayWireframeButton_i(o,v);
}

void GUI::cb_DisplayNormalsButton_i(Fl_Light_Button* o, void*) {
  MVC->SetDisplayNormals(o->value());
}
void GUI::cb_DisplayNormalsButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_DisplayNormalsButton_i(o,v);
}

void GUI::cb_DisplayEndpointsButton_i(Fl_Light_Button* o, void*) {
  MVC->SetDisplayEndpoints(o->value());
}
void GUI::cb_DisplayEndpointsButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_DisplayEndpointsButton_i(o,v);
}

void GUI::cb_PolygonValSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetPolygonVal(o->value());
MVC->redraw();
}
void GUI::cb_PolygonValSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_PolygonValSlider_i(o,v);
}

void GUI::cb_PolygonSatSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetPolygonSat(o->value());
MVC->redraw();
}
void GUI::cb_PolygonSatSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_PolygonSatSlider_i(o,v);
}

void GUI::cb_PolygonHueSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetPolygonHue(o->value());
MVC->redraw();
}
void GUI::cb_PolygonHueSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_PolygonHueSlider_i(o,v);
}

void GUI::cb_WireframeValSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetWireframeVal(o->value());
MVC->redraw();
}
void GUI::cb_WireframeValSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_WireframeValSlider_i(o,v);
}

void GUI::cb_WireframeSatSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetWireframeSat(o->value());
MVC->redraw();
}
void GUI::cb_WireframeSatSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_WireframeSatSlider_i(o,v);
}

void GUI::cb_WireframeHueSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetWireframeHue(o->value());
MVC->redraw();
}
void GUI::cb_WireframeHueSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_WireframeHueSlider_i(o,v);
}

void GUI::cb_NormalValSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetNormalsVal(o->value());
MVC->redraw();
}
void GUI::cb_NormalValSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_NormalValSlider_i(o,v);
}

void GUI::cb_NormalSatSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetNormalsSat(o->value());
MVC->redraw();
}
void GUI::cb_NormalSatSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_NormalSatSlider_i(o,v);
}

void GUI::cb_NormalHueSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetNormalsHue(o->value());
MVC->redraw();
}
void GUI::cb_NormalHueSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_NormalHueSlider_i(o,v);
}

void GUI::cb_EndpointValSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetEndpointsVal(o->value());
MVC->redraw();
}
void GUI::cb_EndpointValSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_EndpointValSlider_i(o,v);
}

void GUI::cb_EndpointSatSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetEndpointsSat(o->value());
MVC->redraw();
}
void GUI::cb_EndpointSatSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_EndpointSatSlider_i(o,v);
}

void GUI::cb_EndpointHueSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetEndpointsHue(o->value());
MVC->redraw();
}
void GUI::cb_EndpointHueSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_EndpointHueSlider_i(o,v);
}

void GUI::cb_DisplayBBoxButton_i(Fl_Light_Button* o, void*) {
  MVC->SetDisplayBBox(o->value());
}
void GUI::cb_DisplayBBoxButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_DisplayBBoxButton_i(o,v);
}

void GUI::cb_HighlightSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetHighlight(o->value());
MVC->redraw();
}
void GUI::cb_HighlightSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_HighlightSlider_i(o,v);
}

void GUI::cb_NormalLengthSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetNormalsLength(o->value());
MVC->redraw();
}
void GUI::cb_NormalLengthSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_NormalLengthSlider_i(o,v);
}

void GUI::cb_EndpointSizeSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetEndPointSize(o->value());
MVC->redraw();
}
void GUI::cb_EndpointSizeSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_EndpointSizeSlider_i(o,v);
}

void GUI::cb_DisplayWireframeShadedButton_i(Fl_Light_Button* o, void*) {
  MVC->SetDisplayWireframeShaded(o->value());
}
void GUI::cb_DisplayWireframeShadedButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_DisplayWireframeShadedButton_i(o,v);
}

void GUI::cb_DisplayGCodeButton_i(Fl_Light_Button* o, void*) {
  MVC->SetDisplayGCode(o->value());
MVC->redraw();
}
void GUI::cb_DisplayGCodeButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_DisplayGCodeButton_i(o,v);
}

void GUI::cb_GCodeExtrudeValSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetGCodeExtrudeVal(o->value());
MVC->redraw();
}
void GUI::cb_GCodeExtrudeValSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_GCodeExtrudeValSlider_i(o,v);
}

void GUI::cb_GCodeExtrudeSatSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetGCodeExtrudeSat(o->value());
MVC->redraw();
}
void GUI::cb_GCodeExtrudeSatSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_GCodeExtrudeSatSlider_i(o,v);
}

void GUI::cb_GCodeExtrudeHueSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetGCodeExtrudeHue(o->value());
MVC->redraw();
}
void GUI::cb_GCodeExtrudeHueSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_GCodeExtrudeHueSlider_i(o,v);
}

void GUI::cb_LuminanceShowsSpeedButton_i(Fl_Light_Button* o, void*) {
  MVC->SetLuminanceShowsSpeed(o->value());
MVC->redraw();
}
void GUI::cb_LuminanceShowsSpeedButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_LuminanceShowsSpeedButton_i(o,v);
}

void GUI::cb_Crop_i(Fl_Button*, void*) {
  float start = GCodeDrawStartSlider->value();
float end = GCodeDrawEndSlider->value();
GCodeDrawStartSlider->range(start,end);
GCodeDrawEndSlider->range(start,end);
GCodeDrawStartSlider->redraw();
GCodeDrawEndSlider->redraw();
}
void GUI::cb_Crop(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_Crop_i(o,v);
}

void GUI::cb_Reset_i(Fl_Button*, void*) {
  GCodeDrawStartSlider->range(0,1);
GCodeDrawEndSlider->range(0,1);
GCodeDrawStartSlider->redraw();
GCodeDrawEndSlider->redraw();
}
void GUI::cb_Reset(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_Reset_i(o,v);
}

void GUI::cb_GCodeDrawStartSlider_i(Fl_Slider* o, void*) {
  MVC->SetGCodeDrawStart(o->value());
}
void GUI::cb_GCodeDrawStartSlider(Fl_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_GCodeDrawStartSlider_i(o,v);
}

void GUI::cb_GCodeDrawEndSlider_i(Fl_Slider* o, void*) {
  MVC->SetGCodeDrawEnd(o->value());
}
void GUI::cb_GCodeDrawEndSlider(Fl_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_GCodeDrawEndSlider_i(o,v);
}

void GUI::cb_GCodeMoveValSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetGCodeMoveVal(o->value());
MVC->redraw();
}
void GUI::cb_GCodeMoveValSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_GCodeMoveValSlider_i(o,v);
}

void GUI::cb_GCodeMoveSatSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetGCodeMoveSat(o->value());
MVC->redraw();
}
void GUI::cb_GCodeMoveSatSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_GCodeMoveSatSlider_i(o,v);
}

void GUI::cb_GCodeMoveHueSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetGCodeMoveHue(o->value());
MVC->redraw();
}
void GUI::cb_GCodeMoveHueSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_GCodeMoveHueSlider_i(o,v);
}

void GUI::cb_CuttingPlaneValueSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetCuttingPlaneValue(o->value());
}
void GUI::cb_CuttingPlaneValueSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_CuttingPlaneValueSlider_i(o,v);
}

void GUI::cb_DisplayCuttingPlaneButton_i(Fl_Light_Button* o, void*) {
  MVC->SetDisplayCuttingPlane(o->value());
}
void GUI::cb_DisplayCuttingPlaneButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_DisplayCuttingPlaneButton_i(o,v);
}

void GUI::cb_DisplayinFillButton_i(Fl_Light_Button* o, void*) {
  MVC->SetDisplayinFill(o->value());
}
void GUI::cb_DisplayinFillButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_DisplayinFillButton_i(o,v);
}

void GUI::cb_DisplayAllLayersButton_i(Fl_Light_Button* o, void*) {
  MVC->SetDisplayAllLayers(o->value());
}
void GUI::cb_DisplayAllLayersButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_DisplayAllLayersButton_i(o,v);
}

void GUI::cb_Enable_i(Fl_Light_Button* o, void*) {
  MVC->SetEnableLight(0, o->value());
}
void GUI::cb_Enable(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_Enable_i(o,v);
}

void GUI::cb_Enable1_i(Fl_Light_Button* o, void*) {
  MVC->SetEnableLight(1, o->value());
}
void GUI::cb_Enable1(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_Enable1_i(o,v);
}

void GUI::cb_Enable2_i(Fl_Light_Button* o, void*) {
  MVC->SetEnableLight(2, o->value());
}
void GUI::cb_Enable2(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_Enable2_i(o,v);
}

void GUI::cb_Enable3_i(Fl_Light_Button* o, void*) {
  MVC->SetEnableLight(3, o->value());
}
void GUI::cb_Enable3(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_Enable3_i(o,v);
}

void GUI::cb_ExamineSlider_i(Fl_Value_Slider* o, void*) {
  MVC->SetExamine(o->value());
}
void GUI::cb_ExamineSlider(Fl_Value_Slider* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_ExamineSlider_i(o,v);
}

void GUI::cb_DisplayDebuginFillButton_i(Fl_Light_Button* o, void*) {
  MVC->SetDisplayDebuginFill(o->value());
}
void GUI::cb_DisplayDebuginFillButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_DisplayDebuginFillButton_i(o,v);
}

void GUI::cb_DisplayDebugButton_i(Fl_Light_Button* o, void*) {
  if(o->value())
{
DisplayDebuginFillButton->show();
ExamineSlider->show();
}
else
{
DisplayDebuginFillButton->hide();
ExamineSlider->hide();
}


MVC->redraw();
}
void GUI::cb_DisplayDebugButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_DisplayDebugButton_i(o,v);
}

void GUI::cb_DrawVertexNumbersButton_i(Fl_Light_Button* o, void*) {
  MVC->SetDrawVertexNumbers(o->value());
}
void GUI::cb_DrawVertexNumbersButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_DrawVertexNumbersButton_i(o,v);
}

void GUI::cb_DrawLineNumbersButton_i(Fl_Light_Button* o, void*) {
  MVC->SetDrawLineNumbers(o->value());
}
void GUI::cb_DrawLineNumbersButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_DrawLineNumbersButton_i(o,v);
}

void GUI::cb_Save2_i(Fl_Button*, void*) {
  Fl_Text_Buffer* buffer = GCodeStart->buffer();
char* pText = buffer->text();
MVC->ProcessControl.GCodeStartText = string(pText);
buffer = GCodeLayer->buffer();
pText = buffer->text();
MVC->ProcessControl.GCodeLayerText = string(pText);
buffer = GCodeEnd->buffer();
pText = buffer->text();
MVC->ProcessControl.GCodeEndText = string(pText);
MVC->ProcessControl.SaveXML();
}
void GUI::cb_Save2(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_Save2_i(o,v);
}

void GUI::cb_ConnectToPrinterButton_i(Fl_Light_Button* o, void*) {
  MVC->ConnectToPrinter(o->value());
}
void GUI::cb_ConnectToPrinterButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_ConnectToPrinterButton_i(o,v);
}

void GUI::cb_PrintButton_i(Fl_Light_Button*, void*) {
  CommunationLog->clear();
MVC->Print();
}
void GUI::cb_PrintButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_PrintButton_i(o,v);
}

void GUI::cb_SwitchHeatOnButton_i(Fl_Light_Button* o, void*) {
  MVC->SwitchHeat(o->value(), TargetTempText->value());
}
void GUI::cb_SwitchHeatOnButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_SwitchHeatOnButton_i(o,v);
}

void GUI::cb_TargetTempText_i(Fl_Value_Input* o, void*) {
  MVC->SetTargetTemp(o->value());
}
void GUI::cb_TargetTempText(Fl_Value_Input* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_TargetTempText_i(o,v);
}

void GUI::cb_RunExtruderButton_i(Fl_Light_Button*, void*) {
  MVC->RunExtruder();
}
void GUI::cb_RunExtruderButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_RunExtruderButton_i(o,v);
}

void GUI::cb_SetExtruderDirectionButton_i(Fl_Light_Button* o, void*) {
  MVC->SetExtruderDirection(o->value());
}
void GUI::cb_SetExtruderDirectionButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_SetExtruderDirectionButton_i(o,v);
}

void GUI::cb_Save3_i(Fl_Button*, void*) {
  Fl_File_Chooser chooser("\\", "*.txt", Fl_File_Chooser::CREATE, "Choose filename");
chooser.show();
while (chooser.shown())
	Fl::wait();
if(chooser.value() == 0)
	return;
std::string dir(chooser.value());


if(dir.length())
{
Fl_Text_Buffer *buffer = Echo->buffer();

int result = buffer->savefile(chooser.value());

switch(result)
{
case 0:	// Succes
break;
case 1:	//Open for write failed
fl_alert("Error saving txt file, error creating file.", "OK");
break;
case 2: // Partially saved file
fl_alert("Error saving txt file, while writing file, is the disk full?.", "OK");
break;
}

MVC->redraw();
};
}
void GUI::cb_Save3(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_Save3_i(o,v);
}

void GUI::cb_ContinueButton_i(Fl_Light_Button*, void*) {
  MVC->Continue();
}
void GUI::cb_ContinueButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_ContinueButton_i(o,v);
}

void GUI::cb_TestButton_i(Fl_Light_Button*, void*) {
  MVC->TestSerial();
}
void GUI::cb_TestButton(Fl_Light_Button* o, void* v) {
  ((GUI*)(o->parent()->parent()->parent()->user_data()))->cb_TestButton_i(o,v);
}

GUI::GUI() {
  { mainWindow = new Fl_Double_Window(1379, 830, "RepSnapper by Kulitorum www.kulitorum.com");
    mainWindow->box(FL_UP_BOX);
    mainWindow->color((Fl_Color)FL_FOREGROUND_COLOR);
    mainWindow->selection_color((Fl_Color)FL_FOREGROUND_COLOR);
    mainWindow->labelsize(12);
    mainWindow->user_data((void*)(this));
    { MVC = new ModelViewController(10, 10, 805, 805, "An instace of ModelViewController");
      MVC->box(FL_UP_BOX);
      MVC->color((Fl_Color)FL_BACKGROUND_COLOR);
      MVC->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      MVC->labeltype(FL_NORMAL_LABEL);
      MVC->labelfont(0);
      MVC->labelsize(14);
      MVC->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
      MVC->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
      MVC->when(FL_WHEN_RELEASE);
    } // ModelViewController* MVC
    { Tabs = new Fl_Tabs(820, 10, 565, 815);
      Tabs->align(FL_ALIGN_TOP_LEFT);
      { Fl_Group* o = new Fl_Group(820, 30, 550, 785, "Input file");
        o->hide();
        { Fl_Button* o = new Fl_Button(835, 40, 145, 25, "Load STL");
          o->callback((Fl_Callback*)cb_Load);
        } // Fl_Button* o
        { FixSTLerrorsButton = new Fl_Light_Button(985, 40, 135, 25, "Fix STL errors");
          FixSTLerrorsButton->value(1);
          FixSTLerrorsButton->selection_color((Fl_Color)FL_GREEN);
          FixSTLerrorsButton->callback((Fl_Callback*)cb_FixSTLerrorsButton);
        } // Fl_Light_Button* FixSTLerrorsButton
        { Fl_Button* o = new Fl_Button(835, 70, 145, 25, "Save STL");
          o->callback((Fl_Callback*)cb_Save);
          o->deactivate();
        } // Fl_Button* o
        { Fl_Button* o = new Fl_Button(835, 100, 145, 25, "Scale model");
          o->callback((Fl_Callback*)cb_Scale);
          o->deactivate();
        } // Fl_Button* o
        { Fl_Group* o = new Fl_Group(830, 765, 535, 50, "Object rotation");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { AutoRotateButton = new Fl_Button(840, 775, 125, 25, "Auto rotate");
            AutoRotateButton->callback((Fl_Callback*)cb_AutoRotateButton);
          } // Fl_Button* AutoRotateButton
          { RotateXButton = new Fl_Button(970, 775, 125, 25, "Rotate X");
            RotateXButton->callback((Fl_Callback*)cb_RotateXButton);
          } // Fl_Button* RotateXButton
          { RotateYButton = new Fl_Button(1100, 775, 125, 25, "Rotate Y");
            RotateYButton->callback((Fl_Callback*)cb_RotateYButton);
          } // Fl_Button* RotateYButton
          { RotateZButton = new Fl_Button(1230, 775, 125, 25, "Rotate Z");
            RotateZButton->callback((Fl_Callback*)cb_RotateZButton);
          } // Fl_Button* RotateZButton
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(820, 30, 550, 765, "Printer definition");
        o->hide();
        { Fl_Group* o = new Fl_Group(830, 55, 230, 40, "Build volume (mm)");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { VolumeX = new Fl_Value_Input(850, 66, 45, 23, "X");
            VolumeX->maximum(5000);
            VolumeX->step(1);
            VolumeX->value(200);
          } // Fl_Value_Input* VolumeX
          { VolumeY = new Fl_Value_Input(925, 66, 45, 23, "Y");
            VolumeY->maximum(5000);
            VolumeY->value(200);
          } // Fl_Value_Input* VolumeY
          { VolumeZ = new Fl_Value_Input(1000, 66, 45, 23, "Z");
            VolumeZ->maximum(5000);
            VolumeZ->value(140);
          } // Fl_Value_Input* VolumeZ
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(1210, 55, 155, 40, "Print margin  (mm)");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { MarginX = new Fl_Value_Input(1235, 66, 45, 23, "X");
            MarginX->maximum(100);
            MarginX->step(1);
            MarginX->value(10);
          } // Fl_Value_Input* MarginX
          { MarginY = new Fl_Value_Input(1310, 66, 45, 23, "Y");
            MarginY->maximum(100);
            MarginY->step(1);
            MarginY->value(10);
          } // Fl_Value_Input* MarginY
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(830, 490, 535, 120, "Acceleration");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { accelerationStepsSlider = new Fl_Value_Slider(840, 540, 515, 20, "Number of acceleration steps");
            accelerationStepsSlider->type(1);
            accelerationStepsSlider->selection_color((Fl_Color)2);
            accelerationStepsSlider->maximum(10);
            accelerationStepsSlider->step(1);
            accelerationStepsSlider->value(5);
            accelerationStepsSlider->textsize(14);
            accelerationStepsSlider->callback((Fl_Callback*)cb_accelerationStepsSlider);
            accelerationStepsSlider->align(FL_ALIGN_TOP_LEFT);
            accelerationStepsSlider->deactivate();
          } // Fl_Value_Slider* accelerationStepsSlider
          { distanceBetweenSpeedStepsSlider = new Fl_Value_Slider(840, 580, 515, 20, "Distance used to read full speed(mm)");
            distanceBetweenSpeedStepsSlider->type(1);
            distanceBetweenSpeedStepsSlider->selection_color((Fl_Color)2);
            distanceBetweenSpeedStepsSlider->maximum(10);
            distanceBetweenSpeedStepsSlider->value(0.1);
            distanceBetweenSpeedStepsSlider->textsize(14);
            distanceBetweenSpeedStepsSlider->callback((Fl_Callback*)cb_distanceBetweenSpeedStepsSlider);
            distanceBetweenSpeedStepsSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* distanceBetweenSpeedStepsSlider
          { EnableAccelerationButton = new Fl_Light_Button(840, 500, 255, 20, "Enable Acceleration");
            EnableAccelerationButton->selection_color((Fl_Color)FL_GREEN);
            EnableAccelerationButton->callback((Fl_Callback*)cb_EnableAccelerationButton);
          } // Fl_Light_Button* EnableAccelerationButton
          { UseFirmwareAccelerationButton = new Fl_Light_Button(1100, 500, 255, 20, "Use Firmware Acceleration");
            UseFirmwareAccelerationButton->selection_color((Fl_Color)FL_GREEN);
            UseFirmwareAccelerationButton->callback((Fl_Callback*)cb_UseFirmwareAccelerationButton);
          } // Fl_Light_Button* UseFirmwareAccelerationButton
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(830, 290, 535, 170, "Print speeds");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { MaxPrintSpeedXYSlider = new Fl_Value_Slider(840, 350, 515, 20, "Max PrintSpeed XY (mm/minute)");
            MaxPrintSpeedXYSlider->type(1);
            MaxPrintSpeedXYSlider->selection_color((Fl_Color)2);
            MaxPrintSpeedXYSlider->maximum(8000);
            MaxPrintSpeedXYSlider->step(100);
            MaxPrintSpeedXYSlider->value(4000);
            MaxPrintSpeedXYSlider->textsize(14);
            MaxPrintSpeedXYSlider->callback((Fl_Callback*)cb_MaxPrintSpeedXYSlider);
            MaxPrintSpeedXYSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* MaxPrintSpeedXYSlider
          { MinPrintSpeedZSlider = new Fl_Value_Slider(840, 390, 515, 20, "Min PrintSpeed Z (mm/minute)");
            MinPrintSpeedZSlider->type(1);
            MinPrintSpeedZSlider->selection_color((Fl_Color)2);
            MinPrintSpeedZSlider->minimum(1);
            MinPrintSpeedZSlider->maximum(2500);
            MinPrintSpeedZSlider->step(10);
            MinPrintSpeedZSlider->value(50);
            MinPrintSpeedZSlider->textsize(14);
            MinPrintSpeedZSlider->callback((Fl_Callback*)cb_MinPrintSpeedZSlider);
            MinPrintSpeedZSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* MinPrintSpeedZSlider
          { MinPrintSpeedXYSlider = new Fl_Value_Slider(840, 310, 515, 20, "Min PrintSpeed XY (mm/minute)");
            MinPrintSpeedXYSlider->type(1);
            MinPrintSpeedXYSlider->selection_color((Fl_Color)2);
            MinPrintSpeedXYSlider->maximum(8000);
            MinPrintSpeedXYSlider->step(100);
            MinPrintSpeedXYSlider->value(1000);
            MinPrintSpeedXYSlider->textsize(14);
            MinPrintSpeedXYSlider->callback((Fl_Callback*)cb_MinPrintSpeedXYSlider);
            MinPrintSpeedXYSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* MinPrintSpeedXYSlider
          { MaxPrintSpeedZSlider = new Fl_Value_Slider(840, 430, 515, 20, "Max PrintSpeed Z (mm/minute)");
            MaxPrintSpeedZSlider->type(1);
            MaxPrintSpeedZSlider->selection_color((Fl_Color)2);
            MaxPrintSpeedZSlider->maximum(2500);
            MaxPrintSpeedZSlider->step(10);
            MaxPrintSpeedZSlider->value(150);
            MaxPrintSpeedZSlider->textsize(14);
            MaxPrintSpeedZSlider->callback((Fl_Callback*)cb_MaxPrintSpeedZSlider);
            MaxPrintSpeedZSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* MaxPrintSpeedZSlider
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(830, 125, 535, 120, "Extruder");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { ExtrudedMaterialWidthSlider = new Fl_Value_Slider(840, 180, 515, 20, "Extruded material width");
            ExtrudedMaterialWidthSlider->type(1);
            ExtrudedMaterialWidthSlider->selection_color((Fl_Color)2);
            ExtrudedMaterialWidthSlider->value(0.7);
            ExtrudedMaterialWidthSlider->textsize(14);
            ExtrudedMaterialWidthSlider->callback((Fl_Callback*)cb_ExtrudedMaterialWidthSlider);
            ExtrudedMaterialWidthSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* ExtrudedMaterialWidthSlider
          { extrusionFactorSlider = new Fl_Value_Slider(840, 220, 515, 20, "Extrusion multiplier");
            extrusionFactorSlider->type(1);
            extrusionFactorSlider->selection_color((Fl_Color)2);
            extrusionFactorSlider->maximum(2);
            extrusionFactorSlider->value(1);
            extrusionFactorSlider->textsize(14);
            extrusionFactorSlider->callback((Fl_Callback*)cb_extrusionFactorSlider);
            extrusionFactorSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* extrusionFactorSlider
          { UseIncrementalEcodeButton = new Fl_Light_Button(840, 135, 515, 20, "Use incremental ecode (for seperate extruder controller)");
            UseIncrementalEcodeButton->selection_color((Fl_Color)FL_GREEN);
            UseIncrementalEcodeButton->callback((Fl_Callback*)cb_UseIncrementalEcodeButton);
          } // Fl_Light_Button* UseIncrementalEcodeButton
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(820, 30, 550, 770, "Infill");
        o->hide();
        { Fl_Group* o = new Fl_Group(830, 55, 540, 250, "Infill");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { InfillRotationSlider = new Fl_Value_Slider(840, 115, 515, 20, "Rotation");
            InfillRotationSlider->type(1);
            InfillRotationSlider->selection_color((Fl_Color)2);
            InfillRotationSlider->maximum(360);
            InfillRotationSlider->step(1);
            InfillRotationSlider->value(45);
            InfillRotationSlider->textsize(14);
            InfillRotationSlider->callback((Fl_Callback*)cb_InfillRotationSlider);
            InfillRotationSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* InfillRotationSlider
          { InfillRotationPrLayerSlider = new Fl_Value_Slider(840, 155, 515, 20, "InFill Rotation pr. Layer");
            InfillRotationPrLayerSlider->type(1);
            InfillRotationPrLayerSlider->selection_color((Fl_Color)2);
            InfillRotationPrLayerSlider->maximum(360);
            InfillRotationPrLayerSlider->step(1);
            InfillRotationPrLayerSlider->value(90);
            InfillRotationPrLayerSlider->textsize(14);
            InfillRotationPrLayerSlider->callback((Fl_Callback*)cb_InfillRotationPrLayerSlider);
            InfillRotationPrLayerSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* InfillRotationPrLayerSlider
          { InfillDistanceSlider = new Fl_Value_Slider(840, 195, 515, 20, "Infill Distance");
            InfillDistanceSlider->type(1);
            InfillDistanceSlider->selection_color((Fl_Color)2);
            InfillDistanceSlider->minimum(0.1);
            InfillDistanceSlider->maximum(10);
            InfillDistanceSlider->step(0.1);
            InfillDistanceSlider->value(2);
            InfillDistanceSlider->textsize(14);
            InfillDistanceSlider->callback((Fl_Callback*)cb_InfillDistanceSlider);
            InfillDistanceSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* InfillDistanceSlider
          { LayerThicknessSlider = new Fl_Value_Slider(840, 235, 515, 20, "Layer Thickness");
            LayerThicknessSlider->type(1);
            LayerThicknessSlider->selection_color((Fl_Color)2);
            LayerThicknessSlider->minimum(0.1);
            LayerThicknessSlider->maximum(3);
            LayerThicknessSlider->step(0.1);
            LayerThicknessSlider->value(0.4);
            LayerThicknessSlider->textsize(14);
            LayerThicknessSlider->callback((Fl_Callback*)cb_LayerThicknessSlider);
            LayerThicknessSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* LayerThicknessSlider
          { OptimizationSlider = new Fl_Value_Slider(840, 275, 515, 20, "Optimize");
            OptimizationSlider->type(1);
            OptimizationSlider->selection_color((Fl_Color)2);
            OptimizationSlider->value(0.01);
            OptimizationSlider->textsize(14);
            OptimizationSlider->callback((Fl_Callback*)cb_OptimizationSlider);
            OptimizationSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* OptimizationSlider
          { ShellOnlyButton = new Fl_Light_Button(840, 75, 255, 20, "Shell Only - no infill");
            ShellOnlyButton->selection_color((Fl_Color)FL_GREEN);
            ShellOnlyButton->callback((Fl_Callback*)cb_ShellOnlyButton);
          } // Fl_Light_Button* ShellOnlyButton
          { ShellCountSlider = new Fl_Value_Slider(1100, 75, 255, 20, "Shell count");
            ShellCountSlider->type(1);
            ShellCountSlider->selection_color((Fl_Color)2);
            ShellCountSlider->minimum(1);
            ShellCountSlider->maximum(10);
            ShellCountSlider->step(1);
            ShellCountSlider->value(1);
            ShellCountSlider->textsize(14);
            ShellCountSlider->callback((Fl_Callback*)cb_ShellCountSlider);
            ShellCountSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* ShellCountSlider
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(820, 30, 550, 765, "Apron");
        o->color((Fl_Color)FL_DARK1);
        o->hide();
        { Fl_Group* o = new Fl_Group(830, 55, 530, 305, "Size");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { ApronSizeSlider = new Fl_Value_Slider(840, 115, 510, 20, "Size");
            ApronSizeSlider->tooltip("How much larget then the print should the Raft be.");
            ApronSizeSlider->type(1);
            ApronSizeSlider->selection_color((Fl_Color)2);
            ApronSizeSlider->minimum(0.1);
            ApronSizeSlider->maximum(2);
            ApronSizeSlider->step(0.1);
            ApronSizeSlider->value(1.3);
            ApronSizeSlider->textsize(14);
            ApronSizeSlider->callback((Fl_Callback*)cb_ApronSizeSlider);
            ApronSizeSlider->align(FL_ALIGN_TOP_LEFT);
            ApronSizeSlider->deactivate();
          } // Fl_Value_Slider* ApronSizeSlider
          { ApronCoverageXSlider = new Fl_Value_Slider(840, 195, 510, 20, "Coverage X axis");
            ApronCoverageXSlider->type(1);
            ApronCoverageXSlider->selection_color((Fl_Color)2);
            ApronCoverageXSlider->minimum(1);
            ApronCoverageXSlider->maximum(100);
            ApronCoverageXSlider->step(1);
            ApronCoverageXSlider->value(30);
            ApronCoverageXSlider->textsize(14);
            ApronCoverageXSlider->callback((Fl_Callback*)cb_ApronCoverageXSlider);
            ApronCoverageXSlider->align(FL_ALIGN_TOP_LEFT);
            ApronCoverageXSlider->deactivate();
          } // Fl_Value_Slider* ApronCoverageXSlider
          { ApronHeightSlider = new Fl_Value_Slider(840, 155, 510, 20, "Height");
            ApronHeightSlider->type(1);
            ApronHeightSlider->selection_color((Fl_Color)2);
            ApronHeightSlider->minimum(1);
            ApronHeightSlider->maximum(30);
            ApronHeightSlider->step(1);
            ApronHeightSlider->value(8);
            ApronHeightSlider->textsize(14);
            ApronHeightSlider->callback((Fl_Callback*)cb_ApronHeightSlider);
            ApronHeightSlider->align(FL_ALIGN_TOP_LEFT);
            ApronHeightSlider->deactivate();
          } // Fl_Value_Slider* ApronHeightSlider
          { ApronCoverageYSlider = new Fl_Value_Slider(840, 235, 510, 20, "Coverage Y axis");
            ApronCoverageYSlider->type(1);
            ApronCoverageYSlider->selection_color((Fl_Color)2);
            ApronCoverageYSlider->minimum(1);
            ApronCoverageYSlider->maximum(100);
            ApronCoverageYSlider->step(1);
            ApronCoverageYSlider->value(30);
            ApronCoverageYSlider->textsize(14);
            ApronCoverageYSlider->callback((Fl_Callback*)cb_ApronCoverageYSlider);
            ApronCoverageYSlider->align(FL_ALIGN_TOP_LEFT);
            ApronCoverageYSlider->deactivate();
          } // Fl_Value_Slider* ApronCoverageYSlider
          { ApronEnableButton = new Fl_Light_Button(840, 75, 250, 20, "Enable");
            ApronEnableButton->callback((Fl_Callback*)cb_ApronEnableButton);
          } // Fl_Light_Button* ApronEnableButton
          { ApronDistanceToObjectSlider = new Fl_Value_Slider(840, 275, 510, 20, "Distance to object");
            ApronDistanceToObjectSlider->type(1);
            ApronDistanceToObjectSlider->selection_color((Fl_Color)2);
            ApronDistanceToObjectSlider->minimum(-1);
            ApronDistanceToObjectSlider->maximum(3);
            ApronDistanceToObjectSlider->step(0.1);
            ApronDistanceToObjectSlider->value(0.5);
            ApronDistanceToObjectSlider->textsize(14);
            ApronDistanceToObjectSlider->callback((Fl_Callback*)cb_ApronDistanceToObjectSlider);
            ApronDistanceToObjectSlider->align(FL_ALIGN_TOP_LEFT);
            ApronDistanceToObjectSlider->deactivate();
          } // Fl_Value_Slider* ApronDistanceToObjectSlider
          { ApronInfillDistanceSlider = new Fl_Value_Slider(840, 315, 510, 20, "Infill Distance");
            ApronInfillDistanceSlider->type(1);
            ApronInfillDistanceSlider->selection_color((Fl_Color)2);
            ApronInfillDistanceSlider->minimum(0.1);
            ApronInfillDistanceSlider->maximum(10);
            ApronInfillDistanceSlider->step(0.1);
            ApronInfillDistanceSlider->value(2);
            ApronInfillDistanceSlider->textsize(14);
            ApronInfillDistanceSlider->callback((Fl_Callback*)cb_ApronInfillDistanceSlider);
            ApronInfillDistanceSlider->align(FL_ALIGN_TOP_LEFT);
            ApronInfillDistanceSlider->deactivate();
          } // Fl_Value_Slider* ApronInfillDistanceSlider
          { ApronPreviewButton = new Fl_Light_Button(1095, 75, 255, 20, "Preview");
            ApronPreviewButton->callback((Fl_Callback*)cb_ApronPreviewButton);
            ApronPreviewButton->deactivate();
          } // Fl_Light_Button* ApronPreviewButton
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(820, 30, 550, 765, "Raft");
        o->color((Fl_Color)FL_DARK1);
        o->hide();
        { Fl_Group* o = new Fl_Group(825, 210, 535, 270, "Base");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { RaftMaterialPrDistanceRatioSlider = new Fl_Value_Slider(835, 275, 515, 20, "Material pr. distance ratio");
            RaftMaterialPrDistanceRatioSlider->type(1);
            RaftMaterialPrDistanceRatioSlider->selection_color((Fl_Color)2);
            RaftMaterialPrDistanceRatioSlider->minimum(0.1);
            RaftMaterialPrDistanceRatioSlider->maximum(3);
            RaftMaterialPrDistanceRatioSlider->step(0.1);
            RaftMaterialPrDistanceRatioSlider->value(1.75);
            RaftMaterialPrDistanceRatioSlider->textsize(14);
            RaftMaterialPrDistanceRatioSlider->callback((Fl_Callback*)cb_RaftMaterialPrDistanceRatioSlider);
            RaftMaterialPrDistanceRatioSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* RaftMaterialPrDistanceRatioSlider
          { RaftRotationSlider = new Fl_Value_Slider(835, 315, 515, 20, "Rotation");
            RaftRotationSlider->type(1);
            RaftRotationSlider->selection_color((Fl_Color)2);
            RaftRotationSlider->maximum(360);
            RaftRotationSlider->step(1);
            RaftRotationSlider->value(90);
            RaftRotationSlider->textsize(14);
            RaftRotationSlider->callback((Fl_Callback*)cb_RaftRotationSlider);
            RaftRotationSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* RaftRotationSlider
          { RaftBaseDistanceSlider = new Fl_Value_Slider(835, 360, 515, 20, "Distance between lines");
            RaftBaseDistanceSlider->tooltip("Distance between the base layer\'s lines");
            RaftBaseDistanceSlider->type(1);
            RaftBaseDistanceSlider->selection_color((Fl_Color)2);
            RaftBaseDistanceSlider->minimum(0.1);
            RaftBaseDistanceSlider->maximum(10);
            RaftBaseDistanceSlider->step(0.1);
            RaftBaseDistanceSlider->value(2);
            RaftBaseDistanceSlider->textsize(14);
            RaftBaseDistanceSlider->callback((Fl_Callback*)cb_RaftBaseDistanceSlider);
            RaftBaseDistanceSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* RaftBaseDistanceSlider
          { RaftBaseThicknessSlider = new Fl_Value_Slider(835, 405, 515, 20, "Thinkness ratio");
            RaftBaseThicknessSlider->tooltip("How much thicker or thinner then a normal layer should the raft base be.");
            RaftBaseThicknessSlider->type(1);
            RaftBaseThicknessSlider->selection_color((Fl_Color)2);
            RaftBaseThicknessSlider->minimum(0.1);
            RaftBaseThicknessSlider->maximum(3);
            RaftBaseThicknessSlider->step(0.1);
            RaftBaseThicknessSlider->value(1);
            RaftBaseThicknessSlider->textsize(14);
            RaftBaseThicknessSlider->callback((Fl_Callback*)cb_RaftBaseThicknessSlider);
            RaftBaseThicknessSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* RaftBaseThicknessSlider
          { RaftBaseLayerCountSlider = new Fl_Value_Slider(835, 235, 515, 20, "Number of Base layers");
            RaftBaseLayerCountSlider->type(1);
            RaftBaseLayerCountSlider->selection_color((Fl_Color)2);
            RaftBaseLayerCountSlider->maximum(5);
            RaftBaseLayerCountSlider->step(1);
            RaftBaseLayerCountSlider->value(1);
            RaftBaseLayerCountSlider->textsize(14);
            RaftBaseLayerCountSlider->callback((Fl_Callback*)cb_RaftBaseLayerCountSlider);
            RaftBaseLayerCountSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* RaftBaseLayerCountSlider
          { RaftBaseTemperatureSlider = new Fl_Value_Slider(835, 450, 515, 20, "Temperature ratio");
            RaftBaseTemperatureSlider->tooltip("To make the flow better, you may want to print the base layers hotter then th\
e rest of the print.");
            RaftBaseTemperatureSlider->type(1);
            RaftBaseTemperatureSlider->selection_color((Fl_Color)2);
            RaftBaseTemperatureSlider->minimum(0.1);
            RaftBaseTemperatureSlider->maximum(3);
            RaftBaseTemperatureSlider->value(1.1);
            RaftBaseTemperatureSlider->textsize(14);
            RaftBaseTemperatureSlider->callback((Fl_Callback*)cb_RaftBaseTemperatureSlider);
            RaftBaseTemperatureSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* RaftBaseTemperatureSlider
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(825, 135, 535, 55, "Size");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { RaftSizeSlider = new Fl_Value_Slider(835, 160, 515, 20, "Size");
            RaftSizeSlider->tooltip("How much larget then the print should the Raft be.");
            RaftSizeSlider->type(1);
            RaftSizeSlider->selection_color((Fl_Color)2);
            RaftSizeSlider->minimum(1);
            RaftSizeSlider->maximum(3);
            RaftSizeSlider->value(1.33);
            RaftSizeSlider->textsize(14);
            RaftSizeSlider->callback((Fl_Callback*)cb_RaftSizeSlider);
            RaftSizeSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* RaftSizeSlider
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(825, 510, 535, 285, "Interface");
          o->tooltip("This is the layer(s) connecting to the print itself. Unlike the Base layer, t\
hey should be \"nice\" and with a normal extrusion ratio.");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { RaftInterfaceMaterialPrDistanceRatioSlider = new Fl_Value_Slider(835, 585, 515, 20, "Material pr. distance ratio");
            RaftInterfaceMaterialPrDistanceRatioSlider->type(1);
            RaftInterfaceMaterialPrDistanceRatioSlider->selection_color((Fl_Color)2);
            RaftInterfaceMaterialPrDistanceRatioSlider->minimum(0.1);
            RaftInterfaceMaterialPrDistanceRatioSlider->maximum(3);
            RaftInterfaceMaterialPrDistanceRatioSlider->step(0.1);
            RaftInterfaceMaterialPrDistanceRatioSlider->value(1);
            RaftInterfaceMaterialPrDistanceRatioSlider->textsize(14);
            RaftInterfaceMaterialPrDistanceRatioSlider->callback((Fl_Callback*)cb_RaftInterfaceMaterialPrDistanceRatioSlider);
            RaftInterfaceMaterialPrDistanceRatioSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* RaftInterfaceMaterialPrDistanceRatioSlider
          { RaftRotationPrLayerSlider = new Fl_Value_Slider(835, 630, 515, 20, "Rotation pr. layer");
            RaftRotationPrLayerSlider->type(1);
            RaftRotationPrLayerSlider->selection_color((Fl_Color)2);
            RaftRotationPrLayerSlider->maximum(360);
            RaftRotationPrLayerSlider->step(1);
            RaftRotationPrLayerSlider->value(90);
            RaftRotationPrLayerSlider->textsize(14);
            RaftRotationPrLayerSlider->callback((Fl_Callback*)cb_RaftRotationPrLayerSlider);
            RaftRotationPrLayerSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* RaftRotationPrLayerSlider
          { RaftInterfaceDistanceSlider = new Fl_Value_Slider(835, 675, 515, 20, "Distance between lines");
            RaftInterfaceDistanceSlider->tooltip("Distance between the base layer\'s lines");
            RaftInterfaceDistanceSlider->type(1);
            RaftInterfaceDistanceSlider->selection_color((Fl_Color)2);
            RaftInterfaceDistanceSlider->minimum(0.1);
            RaftInterfaceDistanceSlider->maximum(10);
            RaftInterfaceDistanceSlider->step(0.1);
            RaftInterfaceDistanceSlider->value(2);
            RaftInterfaceDistanceSlider->textsize(14);
            RaftInterfaceDistanceSlider->callback((Fl_Callback*)cb_RaftInterfaceDistanceSlider);
            RaftInterfaceDistanceSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* RaftInterfaceDistanceSlider
          { RaftInterfaceThicknessSlider = new Fl_Value_Slider(835, 720, 515, 20, "Thinkness ratio");
            RaftInterfaceThicknessSlider->tooltip("How much thicker or thinner then a normal layer should the raft base be.");
            RaftInterfaceThicknessSlider->type(1);
            RaftInterfaceThicknessSlider->selection_color((Fl_Color)2);
            RaftInterfaceThicknessSlider->minimum(0.1);
            RaftInterfaceThicknessSlider->maximum(3);
            RaftInterfaceThicknessSlider->step(0.1);
            RaftInterfaceThicknessSlider->value(1);
            RaftInterfaceThicknessSlider->textsize(14);
            RaftInterfaceThicknessSlider->callback((Fl_Callback*)cb_RaftInterfaceThicknessSlider);
            RaftInterfaceThicknessSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* RaftInterfaceThicknessSlider
          { RaftInterfaceLayerCountSlider = new Fl_Value_Slider(835, 540, 515, 20, "Number of interface layers");
            RaftInterfaceLayerCountSlider->type(1);
            RaftInterfaceLayerCountSlider->selection_color((Fl_Color)2);
            RaftInterfaceLayerCountSlider->maximum(5);
            RaftInterfaceLayerCountSlider->step(1);
            RaftInterfaceLayerCountSlider->value(2);
            RaftInterfaceLayerCountSlider->textsize(14);
            RaftInterfaceLayerCountSlider->callback((Fl_Callback*)cb_RaftInterfaceLayerCountSlider);
            RaftInterfaceLayerCountSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* RaftInterfaceLayerCountSlider
          { RaftInterfaceTemperatureSlider = new Fl_Value_Slider(835, 765, 515, 20, "Temperature ratio");
            RaftInterfaceTemperatureSlider->tooltip("To make the flow better, you may want to print the base layers hotter then th\
e rest of the print.");
            RaftInterfaceTemperatureSlider->type(1);
            RaftInterfaceTemperatureSlider->selection_color((Fl_Color)2);
            RaftInterfaceTemperatureSlider->minimum(0.1);
            RaftInterfaceTemperatureSlider->maximum(3);
            RaftInterfaceTemperatureSlider->value(1.1);
            RaftInterfaceTemperatureSlider->textsize(14);
            RaftInterfaceTemperatureSlider->callback((Fl_Callback*)cb_RaftInterfaceTemperatureSlider);
            RaftInterfaceTemperatureSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* RaftInterfaceTemperatureSlider
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(825, 50, 535, 55, "Size");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { RaftEnableButton = new Fl_Light_Button(830, 70, 255, 25, "Enable");
            RaftEnableButton->callback((Fl_Callback*)cb_RaftEnableButton);
          } // Fl_Light_Button* RaftEnableButton
          { Fl_Light_Button* o = new Fl_Light_Button(1090, 70, 255, 25, "Preview");
            o->callback((Fl_Callback*)cb_Preview);
            o->deactivate();
          } // Fl_Light_Button* o
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(830, 40, 550, 785, "GCode");
        o->hide();
        { Fl_Button* o = new Fl_Button(835, 80, 145, 25, "Load Gcode");
          o->callback((Fl_Callback*)cb_Load1);
        } // Fl_Button* o
        { GCodeLengthText = new Fl_Output(985, 81, 225, 24);
        } // Fl_Output* GCodeLengthText
        { Fl_Button* o = new Fl_Button(835, 50, 145, 25, "Convert to GCode");
          o->callback((Fl_Callback*)cb_Convert);
        } // Fl_Button* o
        { Fl_Tabs* o = new Fl_Tabs(830, 110, 550, 715);
          { Fl_Text_Editor* o = GCodeStart = new Fl_Text_Editor(830, 130, 550, 695, "Start code");
            GCodeStart->hide();
            Fl_Text_Buffer *startbuff = new Fl_Text_Buffer();
            o->buffer(startbuff);
          } // Fl_Text_Editor* GCodeStart
          { Fl_Text_Editor* o = GCodeLayer = new Fl_Text_Editor(830, 130, 550, 695, "Next layer");
            GCodeLayer->hide();
            Fl_Text_Buffer *layerbuff = new Fl_Text_Buffer();
            o->buffer(layerbuff);
          } // Fl_Text_Editor* GCodeLayer
          { Fl_Text_Editor* o = GCodeEnd = new Fl_Text_Editor(830, 130, 550, 695, "End code");
            GCodeEnd->hide();
            Fl_Text_Buffer *endbuff = new Fl_Text_Buffer();
            o->buffer(endbuff);
          } // Fl_Text_Editor* GCodeEnd
          { Fl_Text_Editor* o = GCodeResult = new Fl_Text_Editor(830, 130, 550, 695, "Result");
            Fl_Text_Buffer *resultbuff = new Fl_Text_Buffer();
            o->buffer(resultbuff);
          } // Fl_Text_Editor* GCodeResult
          o->end();
        } // Fl_Tabs* o
        { Fl_Button* o = new Fl_Button(1215, 80, 145, 25, "Save Gcode");
          o->callback((Fl_Callback*)cb_Save1);
        } // Fl_Button* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(820, 30, 550, 785, "Score");
        o->hide();
        { new Fl_Button(830, 55, 540, 140, "Placeholder and reminder for antomatic Score\'ing of objects (see todo folder\
)");
        } // Fl_Button* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(820, 30, 550, 780, "Rendering");
        o->color((Fl_Color)FL_DARK1);
        o->hide();
        { Fl_Group* o = new Fl_Group(825, 60, 535, 280, "STL rendering");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { DisplayPolygonsButton = new Fl_Light_Button(860, 70, 220, 20, "Display Polygons");
            DisplayPolygonsButton->value(1);
            DisplayPolygonsButton->selection_color((Fl_Color)FL_GREEN);
            DisplayPolygonsButton->callback((Fl_Callback*)cb_DisplayPolygonsButton);
          } // Fl_Light_Button* DisplayPolygonsButton
          { DisplayWireframeButton = new Fl_Light_Button(1125, 70, 140, 20, "Display Wireframe");
            DisplayWireframeButton->selection_color((Fl_Color)FL_GREEN);
            DisplayWireframeButton->callback((Fl_Callback*)cb_DisplayWireframeButton);
          } // Fl_Light_Button* DisplayWireframeButton
          { DisplayNormalsButton = new Fl_Light_Button(860, 170, 220, 20, "Display Normals");
            DisplayNormalsButton->selection_color((Fl_Color)FL_GREEN);
            DisplayNormalsButton->callback((Fl_Callback*)cb_DisplayNormalsButton);
          } // Fl_Light_Button* DisplayNormalsButton
          { DisplayEndpointsButton = new Fl_Light_Button(1125, 170, 220, 20, "Display Endpoints");
            DisplayEndpointsButton->selection_color((Fl_Color)FL_GREEN);
            DisplayEndpointsButton->callback((Fl_Callback*)cb_DisplayEndpointsButton);
          } // Fl_Light_Button* DisplayEndpointsButton
          { PolygonValSlider = new Fl_Value_Slider(860, 135, 220, 20, "Val");
            PolygonValSlider->type(5);
            PolygonValSlider->selection_color((Fl_Color)2);
            PolygonValSlider->value(0.5);
            PolygonValSlider->textsize(14);
            PolygonValSlider->callback((Fl_Callback*)cb_PolygonValSlider);
            PolygonValSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* PolygonValSlider
          { PolygonSatSlider = new Fl_Value_Slider(860, 115, 220, 20, "Sat");
            PolygonSatSlider->type(5);
            PolygonSatSlider->selection_color((Fl_Color)2);
            PolygonSatSlider->value(0.5);
            PolygonSatSlider->textsize(14);
            PolygonSatSlider->callback((Fl_Callback*)cb_PolygonSatSlider);
            PolygonSatSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* PolygonSatSlider
          { PolygonHueSlider = new Fl_Value_Slider(860, 95, 220, 20, "Hue");
            PolygonHueSlider->type(5);
            PolygonHueSlider->selection_color((Fl_Color)2);
            PolygonHueSlider->value(0.5);
            PolygonHueSlider->textsize(14);
            PolygonHueSlider->callback((Fl_Callback*)cb_PolygonHueSlider);
            PolygonHueSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* PolygonHueSlider
          { WireframeValSlider = new Fl_Value_Slider(1125, 135, 220, 20, "Val");
            WireframeValSlider->type(5);
            WireframeValSlider->selection_color((Fl_Color)2);
            WireframeValSlider->value(0.5);
            WireframeValSlider->textsize(14);
            WireframeValSlider->callback((Fl_Callback*)cb_WireframeValSlider);
            WireframeValSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* WireframeValSlider
          { WireframeSatSlider = new Fl_Value_Slider(1125, 115, 220, 20, "Sat");
            WireframeSatSlider->type(5);
            WireframeSatSlider->selection_color((Fl_Color)2);
            WireframeSatSlider->value(0.5);
            WireframeSatSlider->textsize(14);
            WireframeSatSlider->callback((Fl_Callback*)cb_WireframeSatSlider);
            WireframeSatSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* WireframeSatSlider
          { WireframeHueSlider = new Fl_Value_Slider(1125, 95, 220, 20, "Hue");
            WireframeHueSlider->type(5);
            WireframeHueSlider->selection_color((Fl_Color)2);
            WireframeHueSlider->value(0.5);
            WireframeHueSlider->textsize(14);
            WireframeHueSlider->callback((Fl_Callback*)cb_WireframeHueSlider);
            WireframeHueSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* WireframeHueSlider
          { NormalValSlider = new Fl_Value_Slider(860, 235, 220, 20, "Val");
            NormalValSlider->type(5);
            NormalValSlider->selection_color((Fl_Color)2);
            NormalValSlider->value(0.5);
            NormalValSlider->textsize(14);
            NormalValSlider->callback((Fl_Callback*)cb_NormalValSlider);
            NormalValSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* NormalValSlider
          { NormalSatSlider = new Fl_Value_Slider(860, 215, 220, 20, "Sat");
            NormalSatSlider->type(5);
            NormalSatSlider->selection_color((Fl_Color)2);
            NormalSatSlider->value(0.5);
            NormalSatSlider->textsize(14);
            NormalSatSlider->callback((Fl_Callback*)cb_NormalSatSlider);
            NormalSatSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* NormalSatSlider
          { NormalHueSlider = new Fl_Value_Slider(860, 195, 220, 20, "Hue");
            NormalHueSlider->type(5);
            NormalHueSlider->selection_color((Fl_Color)2);
            NormalHueSlider->value(0.5);
            NormalHueSlider->textsize(14);
            NormalHueSlider->callback((Fl_Callback*)cb_NormalHueSlider);
            NormalHueSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* NormalHueSlider
          { EndpointValSlider = new Fl_Value_Slider(1125, 235, 220, 20, "Val");
            EndpointValSlider->type(5);
            EndpointValSlider->selection_color((Fl_Color)2);
            EndpointValSlider->value(0.5);
            EndpointValSlider->textsize(14);
            EndpointValSlider->callback((Fl_Callback*)cb_EndpointValSlider);
            EndpointValSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* EndpointValSlider
          { EndpointSatSlider = new Fl_Value_Slider(1125, 215, 220, 20, "Sat");
            EndpointSatSlider->type(5);
            EndpointSatSlider->selection_color((Fl_Color)2);
            EndpointSatSlider->value(0.5);
            EndpointSatSlider->textsize(14);
            EndpointSatSlider->callback((Fl_Callback*)cb_EndpointSatSlider);
            EndpointSatSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* EndpointSatSlider
          { EndpointHueSlider = new Fl_Value_Slider(1125, 195, 220, 20, "Hue");
            EndpointHueSlider->type(5);
            EndpointHueSlider->selection_color((Fl_Color)2);
            EndpointHueSlider->value(0.5);
            EndpointHueSlider->textsize(14);
            EndpointHueSlider->callback((Fl_Callback*)cb_EndpointHueSlider);
            EndpointHueSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* EndpointHueSlider
          { DisplayBBoxButton = new Fl_Light_Button(860, 315, 220, 20, "Display Bounding Box");
            DisplayBBoxButton->selection_color((Fl_Color)FL_GREEN);
            DisplayBBoxButton->callback((Fl_Callback*)cb_DisplayBBoxButton);
          } // Fl_Light_Button* DisplayBBoxButton
          { HighlightSlider = new Fl_Value_Slider(1125, 315, 220, 20, "Highlight");
            HighlightSlider->type(5);
            HighlightSlider->selection_color((Fl_Color)2);
            HighlightSlider->value(0.5);
            HighlightSlider->textsize(14);
            HighlightSlider->callback((Fl_Callback*)cb_HighlightSlider);
            HighlightSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* HighlightSlider
          { NormalLengthSlider = new Fl_Value_Slider(860, 275, 220, 20, "Normals length");
            NormalLengthSlider->type(5);
            NormalLengthSlider->selection_color((Fl_Color)2);
            NormalLengthSlider->minimum(1);
            NormalLengthSlider->maximum(30);
            NormalLengthSlider->step(0.1);
            NormalLengthSlider->value(10);
            NormalLengthSlider->textsize(14);
            NormalLengthSlider->callback((Fl_Callback*)cb_NormalLengthSlider);
            NormalLengthSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* NormalLengthSlider
          { EndpointSizeSlider = new Fl_Value_Slider(1125, 275, 220, 20, "Endpoints size");
            EndpointSizeSlider->type(5);
            EndpointSizeSlider->selection_color((Fl_Color)2);
            EndpointSizeSlider->minimum(1);
            EndpointSizeSlider->maximum(20);
            EndpointSizeSlider->step(0.1);
            EndpointSizeSlider->value(8);
            EndpointSizeSlider->textsize(14);
            EndpointSizeSlider->callback((Fl_Callback*)cb_EndpointSizeSlider);
            EndpointSizeSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* EndpointSizeSlider
          { DisplayWireframeShadedButton = new Fl_Light_Button(1270, 70, 75, 20, "Shaded");
            DisplayWireframeShadedButton->selection_color((Fl_Color)FL_GREEN);
            DisplayWireframeShadedButton->callback((Fl_Callback*)cb_DisplayWireframeShadedButton);
          } // Fl_Light_Button* DisplayWireframeShadedButton
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(825, 360, 535, 185, "GCode rendering");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { DisplayGCodeButton = new Fl_Light_Button(860, 370, 220, 20, "Display GCode");
            DisplayGCodeButton->value(1);
            DisplayGCodeButton->selection_color((Fl_Color)FL_GREEN);
            DisplayGCodeButton->callback((Fl_Callback*)cb_DisplayGCodeButton);
          } // Fl_Light_Button* DisplayGCodeButton
          { GCodeExtrudeValSlider = new Fl_Value_Slider(860, 435, 220, 20, "Val");
            GCodeExtrudeValSlider->type(5);
            GCodeExtrudeValSlider->selection_color((Fl_Color)2);
            GCodeExtrudeValSlider->value(0.5);
            GCodeExtrudeValSlider->textsize(14);
            GCodeExtrudeValSlider->callback((Fl_Callback*)cb_GCodeExtrudeValSlider);
            GCodeExtrudeValSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* GCodeExtrudeValSlider
          { GCodeExtrudeSatSlider = new Fl_Value_Slider(860, 415, 220, 20, "Sat");
            GCodeExtrudeSatSlider->type(5);
            GCodeExtrudeSatSlider->selection_color((Fl_Color)2);
            GCodeExtrudeSatSlider->value(0.5);
            GCodeExtrudeSatSlider->textsize(14);
            GCodeExtrudeSatSlider->callback((Fl_Callback*)cb_GCodeExtrudeSatSlider);
            GCodeExtrudeSatSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* GCodeExtrudeSatSlider
          { GCodeExtrudeHueSlider = new Fl_Value_Slider(860, 395, 220, 20, "Hue");
            GCodeExtrudeHueSlider->type(5);
            GCodeExtrudeHueSlider->selection_color((Fl_Color)2);
            GCodeExtrudeHueSlider->value(0.5);
            GCodeExtrudeHueSlider->textsize(14);
            GCodeExtrudeHueSlider->callback((Fl_Callback*)cb_GCodeExtrudeHueSlider);
            GCodeExtrudeHueSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* GCodeExtrudeHueSlider
          { LuminanceShowsSpeedButton = new Fl_Light_Button(1125, 370, 220, 20, "Luminance shows speed");
            LuminanceShowsSpeedButton->value(1);
            LuminanceShowsSpeedButton->selection_color((Fl_Color)FL_GREEN);
            LuminanceShowsSpeedButton->callback((Fl_Callback*)cb_LuminanceShowsSpeedButton);
          } // Fl_Light_Button* LuminanceShowsSpeedButton
          { Fl_Button* o = new Fl_Button(860, 510, 220, 20, "Crop Range");
            o->callback((Fl_Callback*)cb_Crop);
          } // Fl_Button* o
          { Fl_Button* o = new Fl_Button(1130, 510, 220, 20, "Reset crop range");
            o->callback((Fl_Callback*)cb_Reset);
          } // Fl_Button* o
          { GCodeDrawStartSlider = new Fl_Slider(860, 460, 490, 20, "From");
            GCodeDrawStartSlider->type(1);
            GCodeDrawStartSlider->color((Fl_Color)FL_DARK3);
            GCodeDrawStartSlider->selection_color((Fl_Color)2);
            GCodeDrawStartSlider->callback((Fl_Callback*)cb_GCodeDrawStartSlider);
            GCodeDrawStartSlider->align(FL_ALIGN_LEFT);
          } // Fl_Slider* GCodeDrawStartSlider
          { GCodeDrawEndSlider = new Fl_Slider(860, 485, 490, 20, "To");
            GCodeDrawEndSlider->type(1);
            GCodeDrawEndSlider->color((Fl_Color)FL_DARK3);
            GCodeDrawEndSlider->selection_color((Fl_Color)2);
            GCodeDrawEndSlider->callback((Fl_Callback*)cb_GCodeDrawEndSlider);
            GCodeDrawEndSlider->align(FL_ALIGN_LEFT);
          } // Fl_Slider* GCodeDrawEndSlider
          { GCodeMoveValSlider = new Fl_Value_Slider(1125, 435, 220, 20, "Val");
            GCodeMoveValSlider->type(5);
            GCodeMoveValSlider->selection_color((Fl_Color)2);
            GCodeMoveValSlider->value(0.5);
            GCodeMoveValSlider->textsize(14);
            GCodeMoveValSlider->callback((Fl_Callback*)cb_GCodeMoveValSlider);
            GCodeMoveValSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* GCodeMoveValSlider
          { GCodeMoveSatSlider = new Fl_Value_Slider(1125, 415, 220, 20, "Sat");
            GCodeMoveSatSlider->type(5);
            GCodeMoveSatSlider->selection_color((Fl_Color)2);
            GCodeMoveSatSlider->value(0.5);
            GCodeMoveSatSlider->textsize(14);
            GCodeMoveSatSlider->callback((Fl_Callback*)cb_GCodeMoveSatSlider);
            GCodeMoveSatSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* GCodeMoveSatSlider
          { GCodeMoveHueSlider = new Fl_Value_Slider(1125, 395, 220, 20, "Hue");
            GCodeMoveHueSlider->type(5);
            GCodeMoveHueSlider->selection_color((Fl_Color)2);
            GCodeMoveHueSlider->value(0.5);
            GCodeMoveHueSlider->textsize(14);
            GCodeMoveHueSlider->callback((Fl_Callback*)cb_GCodeMoveHueSlider);
            GCodeMoveHueSlider->align(FL_ALIGN_LEFT);
          } // Fl_Value_Slider* GCodeMoveHueSlider
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(825, 575, 540, 90, "Layer preview");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { CuttingPlaneValueSlider = new Fl_Value_Slider(835, 635, 515, 20, "Cuttingplane");
            CuttingPlaneValueSlider->type(1);
            CuttingPlaneValueSlider->value(0.5);
            CuttingPlaneValueSlider->textsize(14);
            CuttingPlaneValueSlider->callback((Fl_Callback*)cb_CuttingPlaneValueSlider);
            CuttingPlaneValueSlider->align(FL_ALIGN_TOP_LEFT);
          } // Fl_Value_Slider* CuttingPlaneValueSlider
          { DisplayCuttingPlaneButton = new Fl_Light_Button(835, 590, 170, 20, "Display CuttingPlane");
            DisplayCuttingPlaneButton->selection_color((Fl_Color)FL_GREEN);
            DisplayCuttingPlaneButton->callback((Fl_Callback*)cb_DisplayCuttingPlaneButton);
          } // Fl_Light_Button* DisplayCuttingPlaneButton
          { DisplayinFillButton = new Fl_Light_Button(1010, 590, 165, 20, "Display inFill");
            DisplayinFillButton->selection_color((Fl_Color)FL_GREEN);
            DisplayinFillButton->callback((Fl_Callback*)cb_DisplayinFillButton);
          } // Fl_Light_Button* DisplayinFillButton
          { DisplayAllLayersButton = new Fl_Light_Button(1180, 590, 170, 20, "Display all layers");
            DisplayAllLayersButton->selection_color((Fl_Color)FL_GREEN);
            DisplayAllLayersButton->callback((Fl_Callback*)cb_DisplayAllLayersButton);
          } // Fl_Light_Button* DisplayAllLayersButton
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(825, 700, 540, 70, "Lights");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { Fl_Light_Button* o = new Fl_Light_Button(835, 715, 120, 20, "Enable light 0");
            o->value(1);
            o->selection_color((Fl_Color)FL_GREEN);
            o->callback((Fl_Callback*)cb_Enable);
          } // Fl_Light_Button* o
          { Fl_Light_Button* o = new Fl_Light_Button(835, 740, 120, 20, "Enable light 1");
            o->selection_color((Fl_Color)FL_GREEN);
            o->callback((Fl_Callback*)cb_Enable1);
          } // Fl_Light_Button* o
          { Fl_Light_Button* o = new Fl_Light_Button(1095, 715, 120, 20, "Enable light 2");
            o->selection_color((Fl_Color)FL_GREEN);
            o->callback((Fl_Callback*)cb_Enable2);
          } // Fl_Light_Button* o
          { Fl_Light_Button* o = new Fl_Light_Button(1095, 740, 120, 20, "Enable light 3");
            o->value(1);
            o->selection_color((Fl_Color)FL_GREEN);
            o->callback((Fl_Callback*)cb_Enable3);
          } // Fl_Light_Button* o
          { Fl_Button* o = new Fl_Button(960, 715, 130, 20, "Edit light 0");
            o->deactivate();
          } // Fl_Button* o
          { Fl_Button* o = new Fl_Button(960, 740, 130, 20, "Edit light 1");
            o->deactivate();
          } // Fl_Button* o
          { Fl_Button* o = new Fl_Button(1220, 715, 130, 20, "Edit light 2");
            o->deactivate();
          } // Fl_Button* o
          { Fl_Button* o = new Fl_Button(1220, 740, 130, 20, "Edit light 3");
            o->deactivate();
          } // Fl_Button* o
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(820, 30, 565, 795, "Debug");
        o->color((Fl_Color)FL_DARK1);
        { ExamineSlider = new Fl_Value_Slider(885, 800, 375, 20, "Examine");
          ExamineSlider->type(1);
          ExamineSlider->step(0.001);
          ExamineSlider->value(0.098);
          ExamineSlider->textsize(14);
          ExamineSlider->callback((Fl_Callback*)cb_ExamineSlider);
          ExamineSlider->align(FL_ALIGN_LEFT);
        } // Fl_Value_Slider* ExamineSlider
        { DisplayDebuginFillButton = new Fl_Light_Button(890, 780, 145, 20, "Display Debug inFill");
          DisplayDebuginFillButton->selection_color((Fl_Color)FL_GREEN);
          DisplayDebuginFillButton->callback((Fl_Callback*)cb_DisplayDebuginFillButton);
        } // Fl_Light_Button* DisplayDebuginFillButton
        { DisplayDebugButton = new Fl_Light_Button(825, 780, 65, 20, "Debug");
          DisplayDebugButton->selection_color((Fl_Color)FL_GREEN);
          DisplayDebugButton->callback((Fl_Callback*)cb_DisplayDebugButton);
        } // Fl_Light_Button* DisplayDebugButton
        { DrawVertexNumbersButton = new Fl_Light_Button(1035, 780, 155, 20, "Draw vertex numbers");
          DrawVertexNumbersButton->selection_color((Fl_Color)FL_GREEN);
          DrawVertexNumbersButton->callback((Fl_Callback*)cb_DrawVertexNumbersButton);
        } // Fl_Light_Button* DrawVertexNumbersButton
        { DrawLineNumbersButton = new Fl_Light_Button(1190, 780, 155, 20, "Draw line numbers");
          DrawLineNumbersButton->selection_color((Fl_Color)FL_GREEN);
          DrawLineNumbersButton->callback((Fl_Callback*)cb_DrawLineNumbersButton);
        } // Fl_Light_Button* DrawLineNumbersButton
        { Fl_Group* o = new Fl_Group(825, 60, 535, 55, "Size");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)FL_DARK3);
          { Fl_Button* o = new Fl_Button(840, 70, 185, 30, "Save settings");
            o->callback((Fl_Callback*)cb_Save2);
          } // Fl_Button* o
          o->end();
        } // Fl_Group* o
        { ConnectToPrinterButton = new Fl_Light_Button(840, 115, 220, 25, "Connect to printer");
          ConnectToPrinterButton->callback((Fl_Callback*)cb_ConnectToPrinterButton);
        } // Fl_Light_Button* ConnectToPrinterButton
        { PrintButton = new Fl_Light_Button(840, 140, 220, 25, "Print");
          PrintButton->callback((Fl_Callback*)cb_PrintButton);
        } // Fl_Light_Button* PrintButton
        { SwitchHeatOnButton = new Fl_Light_Button(840, 165, 220, 25, "Switch heat on");
          SwitchHeatOnButton->callback((Fl_Callback*)cb_SwitchHeatOnButton);
        } // Fl_Light_Button* SwitchHeatOnButton
        { TargetTempText = new Fl_Value_Input(1295, 166, 55, 24, "Target temp");
          TargetTempText->callback((Fl_Callback*)cb_TargetTempText);
        } // Fl_Value_Input* TargetTempText
        { CurrentTempText = new Fl_Value_Output(1150, 166, 55, 24, "Current temp");
        } // Fl_Value_Output* CurrentTempText
        { RunExtruderButton = new Fl_Light_Button(840, 190, 220, 25, "Run extruder");
          RunExtruderButton->callback((Fl_Callback*)cb_RunExtruderButton);
        } // Fl_Light_Button* RunExtruderButton
        { SetExtruderDirectionButton = new Fl_Light_Button(1065, 190, 220, 25, "Reverse");
          SetExtruderDirectionButton->callback((Fl_Callback*)cb_SetExtruderDirectionButton);
        } // Fl_Light_Button* SetExtruderDirectionButton
        { Fl_Tabs* o = new Fl_Tabs(825, 215, 540, 565);
          { CommunationLog = new Fl_Multi_Browser(830, 240, 530, 540, "Communication log");
            CommunationLog->box(FL_NO_BOX);
            CommunationLog->color((Fl_Color)FL_BACKGROUND2_COLOR);
            CommunationLog->selection_color((Fl_Color)FL_SELECTION_COLOR);
            CommunationLog->labeltype(FL_NORMAL_LABEL);
            CommunationLog->labelfont(0);
            CommunationLog->labelsize(14);
            CommunationLog->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
            CommunationLog->align(FL_ALIGN_BOTTOM);
            CommunationLog->when(FL_WHEN_RELEASE_ALWAYS);
            CommunationLog->hide();
          } // Fl_Multi_Browser* CommunationLog
          { ErrorLog = new Fl_Multi_Browser(830, 240, 530, 540, "Errors / warnings");
            ErrorLog->box(FL_NO_BOX);
            ErrorLog->color((Fl_Color)FL_BACKGROUND2_COLOR);
            ErrorLog->selection_color((Fl_Color)FL_SELECTION_COLOR);
            ErrorLog->labeltype(FL_NORMAL_LABEL);
            ErrorLog->labelfont(0);
            ErrorLog->labelsize(14);
            ErrorLog->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
            ErrorLog->align(FL_ALIGN_BOTTOM);
            ErrorLog->when(FL_WHEN_RELEASE_ALWAYS);
            ErrorLog->hide();
          } // Fl_Multi_Browser* ErrorLog
          { Fl_Text_Editor* o = Echo = new Fl_Text_Editor(825, 240, 535, 535, "Echo");
            Fl_Text_Buffer *echobuff = new Fl_Text_Buffer();
            o->buffer(echobuff);
          } // Fl_Text_Editor* Echo
          o->end();
        } // Fl_Tabs* o
        { Fl_Button* o = new Fl_Button(1260, 800, 105, 20, "Save echo log");
          o->callback((Fl_Callback*)cb_Save3);
        } // Fl_Button* o
        { ContinueButton = new Fl_Light_Button(1065, 140, 90, 25, "Continue");
          ContinueButton->callback((Fl_Callback*)cb_ContinueButton);
        } // Fl_Light_Button* ContinueButton
        { TestButton = new Fl_Light_Button(1165, 140, 90, 25, "Test Serial");
          TestButton->callback((Fl_Callback*)cb_TestButton);
        } // Fl_Light_Button* TestButton
        o->end();
      } // Fl_Group* o
      Tabs->end();
    } // Fl_Tabs* Tabs
    mainWindow->end();
    mainWindow->resizable(mainWindow);
  } // Fl_Double_Window* mainWindow
}

void GUI::show(int argc, char **argv) {
  Fl::visual( FL_DOUBLE | FL_RGB);
Fl::scheme("plastic");
mainWindow->show(argc, argv);
//MVC->ReadStl("C:/box.stl");
MVC->init();
MVC->ReadStl("C:/#Downloads/Reprap Exchange/N_DSL-Stylus.stl");
//MVC->ReadStl("C:/code/printed-parts/frame-vertex_6off.stl");
MVC->CopySettingsToGUI();
MVC->draw();
MVC->redraw();
MVC->redraw();
}
